#!/bin/sh

ILS=$1
ROOT=$2

case "$ILS" in
    '') exit 1 ;;
esac

case "$ROOT" in
    '') exit 1 ;;
     /) exit 1 ;;
esac

mkdir -p $ROOT
cp -n -R ./base/* $ROOT
cp -n -R ./$ILS/* $ROOT
pfr init $ROOT/vbdb.sqlite
