#!/usr/bin/perl

use strict;
use warnings;

my ($ILS) = @_;
my @failed;

open STDIN, '<', 'bbin/prereqs' or die "open bbin/prereqs: $!";
print STDERR "Checking required Perl modules...\n";
$/ = '';
while (<STDIN>) {
    s/^\s*#.+\n//mg;
    chomp;
    next if !s/^perlmod //;
    my $ok = eval { eval "use $_; 1" };
    if ($ok) {
        print STDERR " ok  $_\n";
    }
    else {
        print STDERR "FAIL $_ -- missing\n";
        push @failed, $_;
    }
}

if (@failed) {
    my $n = @failed;
    if (open my $fh, '>', 'build/missing') {
        print $fh "perlmod $_\n" for @failed;
    }
    if (@failed == 1) {
        print STDERR "You are missing 1 module.  I can install this for you.\n";
    }
    else {
        print STDERR "You are missing $n modules.  I can install these for you.\n";
    }
}
else {
    print STDERR "You have all the required modules.\n";
    print STDERR "\n";
    exit 0;
}

foreach my $module (@failed) {
    1;
}

exit 1;

__END__
