#!/usr/bin/perl

use strict;
use warnings;

my ($ILS) = @_;
my @failed;

open STDIN, '-|', 'bbin/prereqs' or die "exec bbin/prereqs: $!";
print STDERR "Checking required scripts...\n";
$/ = '';
while (<STDIN>) {
    s/^\s*#.+\n//mg;
    chomp;
    next if !s/^script // && !s/^script.$ILS //;
    my $ok = eval { eval "use $_; 1" };
    if ($ok) {
        print STDERR " ok  $_\n";
    }
    else {
        print STDERR "FAIL $_ -- missing\n";
        push @failed, $_;
    }
}

if (@failed) {
    my $n = @failed;
    if (open my $fh, '>', 'build/missing') {
        print $fh "script $_\n" for @failed;
    }
    if (@failed == 1) {
        print STDERR "You are missing 1 script.  I can install this for you.\n";
    }
    else {
        print STDERR "You are missing $n scripts.  I can install these for you.\n";
    }
}
else {
    print STDERR "You have all the required scripts.\n";
    print STDERR "\n";
    exit 0;
}

foreach my $script (@failed) {
    1;
}

exit 1;

