#!/bin/sh

ILS=$1
PREFIX=$2
ROOT=$3
shift 3

err=0

bbin/check-syntax $scripts || err=1
PERL5LIB=$ROOT/lib bbin/check-prereqs perlmod $ILS $PREFIX $ROOT || err=1
bbin/check-prereqs script $ILS $PREFIX $ROOT || err=1

exit $err
