#!/bin/sh

### Don't edit this file; it's generated automatically

ILS=$1
ROOT=$2

# Perl modules that vblr itself needs
cat <<EOS
perlmod Cwd

perlmod DB_File

perlmod Digest::SHA1

perlmod File::Basename

perlmod File::Copy

perlmod File::Kit

perlmod File::Kvpar

perlmod File::Spec

perlmod Getopt::Long

perlmod IO::Compress::Gzip

perlmod IO::Handle

perlmod MIME::Base64

perlmod POSIX

perlmod String::Expando

perlmod String::ShellQuote

perlmod Text::Glob

perlmod Text::ParseWords

perlmod Time::HiRes

perlmod YAML

EOS

# Scripts that vblr calls
cat <<EOS
script marcn

script marcdiag

EOS

# Perl modules that those scripts require
cat <<EOS
perlmod MARC::Loop

EOS
